baseURL = "https://edoardoinamo.dev/"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
theme = "PaperMod"
title = "Edoardo Inamo"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

pagination.pagerSize = 5

[params]
    name = "Edoardo Inamo"
    author = "Edoardo Inamo"
    profilePicture = "images/profile.jpg"
    year = 2017
    avatar = "images/profile.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/landscape.jpg"
    favicon = "favicons/"
    DateForm = "January 2, 2006"
    localizedDates = true
    disableTitleCapitalization = true

    reversepagetitle = true
    doNotLoadAnimations = true
    #contentratio = 0.7
    disableThemeSwitcher = false
    disableArchiveTitleStyling = true
    displayMode = "dark"

    fullPostContent = false

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[params.profileMode]
    enabled = true
    imageUrl = "images/profile.jpg"
    imageTitle = "Edoardo's profile image"
    imageWidth = 250
    imageHeight = 250
    


[languages]

[languages.it]
    weight = 1
    languageCode = "it"
    languageName = "Ita"
    contentDir = "content/italian"

[languages.it.params]
    pivaDesc = "P.IVA"
    pivaNumber = "IT10939260963"

[languages.it.params.profileMode]
    title = "Edoardo Inamo"
    subtitle = "Product-Minded Software Developer"
    description = "Converto le esigenze dei clienti in prodotti digitali che soddisfano gli utenti"

[[languages.it.menu.main]]
    name = "Home"
    identifier = "home"
    url = "/it/"
    weight = 100
    
[[languages.it.menu.main]]
    name = "Chi Sono"
    weight = 400
    identifier = "about"
    url = "/it/about/"

[[languages.it.menu.main]]
    name = "Servizi"
    weight = 500
    identifier = "services"
    url = "/it/services/"

[languages.en]
    weight = 2
    languageCode = "en"
    languageName = "Eng"
    contentDir = "content/english"
    
[languages.en.params]
    pivaDesc = "VATIN"
    pivaNumber = "IT10939260963"

[languages.en.params.profileMode]
    title = "Edoardo Inamo"
    subtitle = "Product-Minded Software Developer"
    description = "Converting customers needs into digital products that delight users"

[[languages.en.menu.main]]
    name = "Home"
    identifier = "home"
    url = "/en/"
    weight = 100
    
[[languages.en.menu.main]]
    name = "About"
    identifier = "about"
    weight = 400
    url = "/en/about/"

[[languages.en.menu.main]]
    name = "Services"
    weight = 500
    identifier = "services"
    url = "/en/services/"



[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"



[[params.socialIcons]]
	name = "linkedin"
    title = "LinkedIn"
	url = "https://www.linkedin.com/in/edoardo-inamo-2431168"
[[params.socialIcons]]
    name = "github"
	title = "GitHub"
	url = "https://github.com/kingsor"
[[params.socialIcons]]
	name = "bluesky"
    title = "Bluesky"
	url = "https://bsky.app/profile/edoardoinamo.bsky.social"
[[params.socialIcons]]
	name = "dev"
    title = "DEV.to"
	url = "https://dev.to/kingsor"


